# Generated by Django 4.2.7 on 2023-11-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nichanchi', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('rasim', models.ImageField(default='', upload_to='')),
                ('body', models.TextField()),
            ],
        ),
    ]
