# Generated by Django 4.2.3 on 2023-11-28 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=40)),
                ('toptitle', models.CharField(max_length=250)),
                ('urtatitle', models.CharField(max_length=250)),
                ('bottomtitle', models.CharField(max_length=250)),
                ('span', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='darsproject',
            name='vaqt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 28, 20, 41, 5, 758552)),
        ),
    ]
