# Generated by Django 4.2.3 on 2023-11-28 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_projects_darsproject_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darsproject',
            name='vaqt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 28, 21, 4, 35, 303530)),
        ),
    ]
