# Generated by Django 4.2.3 on 2023-11-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darsliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.CharField(max_length=60)),
                ('mavzu', models.CharField(blank=True, max_length=250, null=True)),
                ('dars', models.TextField()),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('rasim', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
